CREATE TABLE tableName 
(
    nombre	varchar(300),
    name	varchar(300),
    nom	varchar(300),
    iso2	varchar(300),
    iso3	varchar(300),
    phone_code	varchar(300)
);

INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Afganistán"', '"Afghanistan"', '"Afghanistan"', '"AF"', '"AFG"', '"93"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Albania"', '"Albania"', '"Albanie"', '"AL"', '"ALB"', '"355"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Alemania"', '"Germany"', '"Allemagne"', '"DE"', '"DEU"', '"49"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Algeria"', '"Algeria"', '"Algérie"', '"DZ"', '"DZA"', '"213"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Andorra"', '"Andorra"', '"Andorra"', '"AD"', '"AND"', '"376"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Angola"', '"Angola"', '"Angola"', '"AO"', '"AGO"', '"244"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Anguila"', '"Anguilla"', '"Anguilla"', '"AI"', '"AIA"', '"1 264"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Antártida"', '"Antarctica"', '"L\'Antarctique"', '"AQ"', '"ATA"', '"672"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Antigua y Barbuda"', '"Antigua and Barbuda"', '"Antigua et Barbuda"', '"AG"', '"ATG"', '"1 268"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Antillas Neerlandesas"', '"Netherlands Antilles"', '"Antilles Néerlandaises"', '"AN"', '"ANT"', '"599"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Arabia Saudita"', '"Saudi Arabia"', '"Arabie Saoudite"', '"SA"', '"SAU"', '"966"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Argentina"', '"Argentina"', '"Argentine"', '"AR"', '"ARG"', '"54"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Armenia"', '"Armenia"', '"L\'Arménie"', '"AM"', '"ARM"', '"374"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Aruba"', '"Aruba"', '"Aruba"', '"AW"', '"ABW"', '"297"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Australia"', '"Australia"', '"Australie"', '"AU"', '"AUS"', '"61"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Austria"', '"Austria"', '"Autriche"', '"AT"', '"AUT"', '"43"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Azerbayán"', '"Azerbaijan"', '"L\'Azerbaïdjan"', '"AZ"', '"AZE"', '"994"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Bélgica"', '"Belgium"', '"Belgique"', '"BE"', '"BEL"', '"32"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Bahamas"', '"Bahamas"', '"Bahamas"', '"BS"', '"BHS"', '"1 242"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Bahrein"', '"Bahrain"', '"Bahreïn"', '"BH"', '"BHR"', '"973"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Bangladesh"', '"Bangladesh"', '"Bangladesh"', '"BD"', '"BGD"', '"880"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Barbados"', '"Barbados"', '"Barbade"', '"BB"', '"BRB"', '"1 246"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Belice"', '"Belize"', '"Belize"', '"BZ"', '"BLZ"', '"501"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Benín"', '"Benin"', '"Bénin"', '"BJ"', '"BEN"', '"229"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Bhután"', '"Bhutan"', '"Le Bhoutan"', '"BT"', '"BTN"', '"975"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Bielorrusia"', '"Belarus"', '"Biélorussie"', '"BY"', '"BLR"', '"375"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Birmania"', '"Myanmar"', '"Myanmar"', '"MM"', '"MMR"', '"95"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Bolivia"', '"Bolivia"', '"Bolivie"', '"BO"', '"BOL"', '"591"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Bosnia y Herzegovina"', '"Bosnia and Herzegovina"', '"Bosnie-Herzégovine"', '"BA"', '"BIH"', '"387"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Botsuana"', '"Botswana"', '"Botswana"', '"BW"', '"BWA"', '"267"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Brasil"', '"Brazil"', '"Brésil"', '"BR"', '"BRA"', '"55"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Brunéi"', '"Brunei"', '"Brunei"', '"BN"', '"BRN"', '"673"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Bulgaria"', '"Bulgaria"', '"Bulgarie"', '"BG"', '"BGR"', '"359"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Burkina Faso"', '"Burkina Faso"', '"Burkina Faso"', '"BF"', '"BFA"', '"226"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Burundi"', '"Burundi"', '"Burundi"', '"BI"', '"BDI"', '"257"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Cabo Verde"', '"Cape Verde"', '"Cap-Vert"', '"CV"', '"CPV"', '"238"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Camboya"', '"Cambodia"', '"Cambodge"', '"KH"', '"KHM"', '"855"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Camerún"', '"Cameroon"', '"Cameroun"', '"CM"', '"CMR"', '"237"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Canadá"', '"Canada"', '"Canada"', '"CA"', '"CAN"', '"1"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Chad"', '"Chad"', '"Tchad"', '"TD"', '"TCD"', '"235"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Chile"', '"Chile"', '"Chili"', '"CL"', '"CHL"', '"56"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"China"', '"China"', '"Chine"', '"CN"', '"CHN"', '"86"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Chipre"', '"Cyprus"', '"Chypre"', '"CY"', '"CYP"', '"357"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Ciudad del Vaticano"', '"Vatican City State"', '"Cité du Vatican"', '"VA"', '"VAT"', '"39"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Colombia"', '"Colombia"', '"Colombie"', '"CO"', '"COL"', '"57"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Comoras"', '"Comoros"', '"Comores"', '"KM"', '"COM"', '"269"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Congo"', '"Congo"', '"Congo"', '"CG"', '"COG"', '"242"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Congo"', '"Congo"', '"Congo"', '"CD"', '"COD"', '"243"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Corea del Norte"', '"North Korea"', '"Corée du Nord"', '"KP"', '"PRK"', '"850"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Corea del Sur"', '"South Korea"', '"Corée du Sud"', '"KR"', '"KOR"', '"82"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Costa de Marfil"', '"Ivory Coast"', '"Côte-d\'Ivoire"', '"CI"', '"CIV"', '"225"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Costa Rica"', '"Costa Rica"', '"Costa Rica"', '"CR"', '"CRI"', '"506"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Croacia"', '"Croatia"', '"Croatie"', '"HR"', '"HRV"', '"385"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Cuba"', '"Cuba"', '"Cuba"', '"CU"', '"CUB"', '"53"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Dinamarca"', '"Denmark"', '"Danemark"', '"DK"', '"DNK"', '"45"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Dominica"', '"Dominica"', '"Dominique"', '"DM"', '"DMA"', '"1 767"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Ecuador"', '"Ecuador"', '"Equateur"', '"EC"', '"ECU"', '"593"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Egipto"', '"Egypt"', '"Egypte"', '"EG"', '"EGY"', '"20"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"El Salvador"', '"El Salvador"', '"El Salvador"', '"SV"', '"SLV"', '"503"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Emiratos Árabes Unidos"', '"United Arab Emirates"', '"Emirats Arabes Unis"', '"AE"', '"ARE"', '"971"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Eritrea"', '"Eritrea"', '"Erythrée"', '"ER"', '"ERI"', '"291"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Eslovaquia"', '"Slovakia"', '"Slovaquie"', '"SK"', '"SVK"', '"421"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Eslovenia"', '"Slovenia"', '"Slovénie"', '"SI"', '"SVN"', '"386"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"España"', '"Spain"', '"Espagne"', '"ES"', '"ESP"', '"34"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Estados Unidos de América"', '"United States of America"', '"États-Unis d\'Amérique"', '"US"', '"USA"', '"1"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Estonia"', '"Estonia"', '"L\'Estonie"', '"EE"', '"EST"', '"372"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Etiopía"', '"Ethiopia"', '"Ethiopie"', '"ET"', '"ETH"', '"251"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Filipinas"', '"Philippines"', '"Philippines"', '"PH"', '"PHL"', '"63"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Finlandia"', '"Finland"', '"Finlande"', '"FI"', '"FIN"', '"358"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Fiyi"', '"Fiji"', '"Fidji"', '"FJ"', '"FJI"', '"679"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Francia"', '"France"', '"France"', '"FR"', '"FRA"', '"33"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Gabón"', '"Gabon"', '"Gabon"', '"GA"', '"GAB"', '"241"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Gambia"', '"Gambia"', '"Gambie"', '"GM"', '"GMB"', '"220"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Georgia"', '"Georgia"', '"Géorgie"', '"GE"', '"GEO"', '"995"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Ghana"', '"Ghana"', '"Ghana"', '"GH"', '"GHA"', '"233"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Gibraltar"', '"Gibraltar"', '"Gibraltar"', '"GI"', '"GIB"', '"350"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Granada"', '"Grenada"', '"Grenade"', '"GD"', '"GRD"', '"1 473"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Grecia"', '"Greece"', '"Grèce"', '"GR"', '"GRC"', '"30"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Groenlandia"', '"Greenland"', '"Groenland"', '"GL"', '"GRL"', '"299"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Guadalupe"', '"Guadeloupe"', '"Guadeloupe"', '"GP"', '"GLP"', '""');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Guam"', '"Guam"', '"Guam"', '"GU"', '"GUM"', '"1 671"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Guatemala"', '"Guatemala"', '"Guatemala"', '"GT"', '"GTM"', '"502"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Guayana Francesa"', '"French Guiana"', '"Guyane française"', '"GF"', '"GUF"', '""');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Guernsey"', '"Guernsey"', '"Guernesey"', '"GG"', '"GGY"', '""');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Guinea"', '"Guinea"', '"Guinée"', '"GN"', '"GIN"', '"224"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Guinea Ecuatorial"', '"Equatorial Guinea"', '"Guinée Equatoriale"', '"GQ"', '"GNQ"', '"240"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Guinea-Bissau"', '"Guinea-Bissau"', '"Guinée-Bissau"', '"GW"', '"GNB"', '"245"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Guyana"', '"Guyana"', '"Guyane"', '"GY"', '"GUY"', '"592"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Haití"', '"Haiti"', '"Haïti"', '"HT"', '"HTI"', '"509"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Honduras"', '"Honduras"', '"Honduras"', '"HN"', '"HND"', '"504"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Hong kong"', '"Hong Kong"', '"Hong Kong"', '"HK"', '"HKG"', '"852"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Hungría"', '"Hungary"', '"Hongrie"', '"HU"', '"HUN"', '"36"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"India"', '"India"', '"Inde"', '"IN"', '"IND"', '"91"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Indonesia"', '"Indonesia"', '"Indonésie"', '"ID"', '"IDN"', '"62"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Irán"', '"Iran"', '"Iran"', '"IR"', '"IRN"', '"98"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Irak"', '"Iraq"', '"Irak"', '"IQ"', '"IRQ"', '"964"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Irlanda"', '"Ireland"', '"Irlande"', '"IE"', '"IRL"', '"353"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Isla Bouvet"', '"Bouvet Island"', '"Bouvet Island"', '"BV"', '"BVT"', '""');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Isla de Man"', '"Isle of Man"', '"Ile de Man"', '"IM"', '"IMN"', '"44"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Isla de Navidad"', '"Christmas Island"', '"Christmas Island"', '"CX"', '"CXR"', '"61"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Isla Norfolk"', '"Norfolk Island"', '"Île de Norfolk"', '"NF"', '"NFK"', '""');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islandia"', '"Iceland"', '"Islande"', '"IS"', '"ISL"', '"354"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas Bermudas"', '"Bermuda Islands"', '"Bermudes"', '"BM"', '"BMU"', '"1 441"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas Caimán"', '"Cayman Islands"', '"Iles Caïmans"', '"KY"', '"CYM"', '"1 345"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas Cocos (Keeling)"', '"Cocos (Keeling) Islands"', '"Cocos (Keeling"', '"CC"', '"CCK"', '"61"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas Cook"', '"Cook Islands"', '"Iles Cook"', '"CK"', '"COK"', '"682"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas de Åland"', '"Åland Islands"', '"Îles Åland"', '"AX"', '"ALA"', '""');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas Feroe"', '"Faroe Islands"', '"Iles Féro"', '"FO"', '"FRO"', '"298"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas Georgias del Sur y Sandwich del Sur"', '"South Georgia and the South Sandwich Islands"', '"Géorgie du Sud et les Îles Sandwich du Sud"', '"GS"', '"SGS"', '""');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas Heard y McDonald"', '"Heard Island and McDonald Islands"', '"Les îles Heard et McDonald"', '"HM"', '"HMD"', '""');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas Maldivas"', '"Maldives"', '"Maldives"', '"MV"', '"MDV"', '"960"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas Malvinas"', '"Falkland Islands (Malvinas)"', '"Iles Falkland (Malvinas"', '"FK"', '"FLK"', '"500"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas Marianas del Norte"', '"Northern Mariana Islands"', '"Iles Mariannes du Nord"', '"MP"', '"MNP"', '"1 670"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas Marshall"', '"Marshall Islands"', '"Iles Marshall"', '"MH"', '"MHL"', '"692"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas Pitcairn"', '"Pitcairn Islands"', '"Iles Pitcairn"', '"PN"', '"PCN"', '"870"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas Salomón"', '"Solomon Islands"', '"Iles Salomon"', '"SB"', '"SLB"', '"677"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas Turcas y Caicos"', '"Turks and Caicos Islands"', '"Iles Turques et Caïques"', '"TC"', '"TCA"', '"1 649"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas Ultramarinas Menores de Estados Unidos"', '"United States Minor Outlying Islands"', '"États-Unis Îles mineures éloignées"', '"UM"', '"UMI"', '""');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas Vírgenes Británicas"', '"Virgin Islands"', '"Iles Vierges"', '"VG"', '"VG"', '"1 284"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Islas Vírgenes de los Estados Unidos"', '"United States Virgin Islands"', '"Îles Vierges américaines"', '"VI"', '"VIR"', '"1 340"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Israel"', '"Israel"', '"Israël"', '"IL"', '"ISR"', '"972"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Italia"', '"Italy"', '"Italie"', '"IT"', '"ITA"', '"39"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Jamaica"', '"Jamaica"', '"Jamaïque"', '"JM"', '"JAM"', '"1 876"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Japón"', '"Japan"', '"Japon"', '"JP"', '"JPN"', '"81"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Jersey"', '"Jersey"', '"Maillot"', '"JE"', '"JEY"', '""');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Jordania"', '"Jordan"', '"Jordan"', '"JO"', '"JOR"', '"962"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Kazajistán"', '"Kazakhstan"', '"Le Kazakhstan"', '"KZ"', '"KAZ"', '"7"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Kenia"', '"Kenya"', '"Kenya"', '"KE"', '"KEN"', '"254"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Kirgizstán"', '"Kyrgyzstan"', '"Kirghizstan"', '"KG"', '"KGZ"', '"996"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Kiribati"', '"Kiribati"', '"Kiribati"', '"KI"', '"KIR"', '"686"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Kuwait"', '"Kuwait"', '"Koweït"', '"KW"', '"KWT"', '"965"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Líbano"', '"Lebanon"', '"Liban"', '"LB"', '"LBN"', '"961"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Laos"', '"Laos"', '"Laos"', '"LA"', '"LAO"', '"856"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Lesoto"', '"Lesotho"', '"Lesotho"', '"LS"', '"LSO"', '"266"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Letonia"', '"Latvia"', '"La Lettonie"', '"LV"', '"LVA"', '"371"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Liberia"', '"Liberia"', '"Liberia"', '"LR"', '"LBR"', '"231"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Libia"', '"Libya"', '"Libye"', '"LY"', '"LBY"', '"218"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Liechtenstein"', '"Liechtenstein"', '"Liechtenstein"', '"LI"', '"LIE"', '"423"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Lituania"', '"Lithuania"', '"La Lituanie"', '"LT"', '"LTU"', '"370"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Luxemburgo"', '"Luxembourg"', '"Luxembourg"', '"LU"', '"LUX"', '"352"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"México"', '"Mexico"', '"Mexique"', '"MX"', '"MEX"', '"52"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Mónaco"', '"Monaco"', '"Monaco"', '"MC"', '"MCO"', '"377"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Macao"', '"Macao"', '"Macao"', '"MO"', '"MAC"', '"853"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Macedônia"', '"Macedonia"', '"Macédoine"', '"MK"', '"MKD"', '"389"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Madagascar"', '"Madagascar"', '"Madagascar"', '"MG"', '"MDG"', '"261"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Malasia"', '"Malaysia"', '"Malaisie"', '"MY"', '"MYS"', '"60"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Malawi"', '"Malawi"', '"Malawi"', '"MW"', '"MWI"', '"265"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Mali"', '"Mali"', '"Mali"', '"ML"', '"MLI"', '"223"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Malta"', '"Malta"', '"Malte"', '"MT"', '"MLT"', '"356"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Marruecos"', '"Morocco"', '"Maroc"', '"MA"', '"MAR"', '"212"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Martinica"', '"Martinique"', '"Martinique"', '"MQ"', '"MTQ"', '""');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Mauricio"', '"Mauritius"', '"Iles Maurice"', '"MU"', '"MUS"', '"230"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Mauritania"', '"Mauritania"', '"Mauritanie"', '"MR"', '"MRT"', '"222"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Mayotte"', '"Mayotte"', '"Mayotte"', '"YT"', '"MYT"', '"262"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Micronesia"', '"Estados Federados de"', '"Federados Estados de"', '"FM"', '"FSM"', '"691"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Moldavia"', '"Moldova"', '"Moldavie"', '"MD"', '"MDA"', '"373"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Mongolia"', '"Mongolia"', '"Mongolie"', '"MN"', '"MNG"', '"976"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Montenegro"', '"Montenegro"', '"Monténégro"', '"ME"', '"MNE"', '"382"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Montserrat"', '"Montserrat"', '"Montserrat"', '"MS"', '"MSR"', '"1 664"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Mozambique"', '"Mozambique"', '"Mozambique"', '"MZ"', '"MOZ"', '"258"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Namibia"', '"Namibia"', '"Namibie"', '"NA"', '"NAM"', '"264"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Nauru"', '"Nauru"', '"Nauru"', '"NR"', '"NRU"', '"674"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Nepal"', '"Nepal"', '"Népal"', '"NP"', '"NPL"', '"977"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Nicaragua"', '"Nicaragua"', '"Nicaragua"', '"NI"', '"NIC"', '"505"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Niger"', '"Niger"', '"Niger"', '"NE"', '"NER"', '"227"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Nigeria"', '"Nigeria"', '"Nigeria"', '"NG"', '"NGA"', '"234"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Niue"', '"Niue"', '"Niou"', '"NU"', '"NIU"', '"683"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Noruega"', '"Norway"', '"Norvège"', '"NO"', '"NOR"', '"47"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Nueva Caledonia"', '"New Caledonia"', '"Nouvelle-Calédonie"', '"NC"', '"NCL"', '"687"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Nueva Zelanda"', '"New Zealand"', '"Nouvelle-Zélande"', '"NZ"', '"NZL"', '"64"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Omán"', '"Oman"', '"Oman"', '"OM"', '"OMN"', '"968"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Países Bajos"', '"Netherlands"', '"Pays-Bas"', '"NL"', '"NLD"', '"31"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Pakistán"', '"Pakistan"', '"Pakistan"', '"PK"', '"PAK"', '"92"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Palau"', '"Palau"', '"Palau"', '"PW"', '"PLW"', '"680"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Palestina"', '"Palestine"', '"La Palestine"', '"PS"', '"PSE"', '""');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Panamá"', '"Panama"', '"Panama"', '"PA"', '"PAN"', '"507"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Papúa Nueva Guinea"', '"Papua New Guinea"', '"Papouasie-Nouvelle-Guinée"', '"PG"', '"PNG"', '"675"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Paraguay"', '"Paraguay"', '"Paraguay"', '"PY"', '"PRY"', '"595"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Perú"', '"Peru"', '"Pérou"', '"PE"', '"PER"', '"51"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Polinesia Francesa"', '"French Polynesia"', '"Polynésie française"', '"PF"', '"PYF"', '"689"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Polonia"', '"Poland"', '"Pologne"', '"PL"', '"POL"', '"48"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Portugal"', '"Portugal"', '"Portugal"', '"PT"', '"PRT"', '"351"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Puerto Rico"', '"Puerto Rico"', '"Porto Rico"', '"PR"', '"PRI"', '"1"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Qatar"', '"Qatar"', '"Qatar"', '"QA"', '"QAT"', '"974"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Reino Unido"', '"United Kingdom"', '"Royaume-Uni"', '"GB"', '"GBR"', '"44"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"República Centroafricana"', '"Central African Republic"', '"République Centrafricaine"', '"CF"', '"CAF"', '"236"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"República Checa"', '"Czech Republic"', '"République Tchèque"', '"CZ"', '"CZE"', '"420"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"República Dominicana"', '"Dominican Republic"', '"République Dominicaine"', '"DO"', '"DOM"', '"1 809"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Reunión"', '"Réunion"', '"Réunion"', '"RE"', '"REU"', '""');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Ruanda"', '"Rwanda"', '"Rwanda"', '"RW"', '"RWA"', '"250"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Rumanía"', '"Romania"', '"Roumanie"', '"RO"', '"ROU"', '"40"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Rusia"', '"Russia"', '"La Russie"', '"RU"', '"RUS"', '"7"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Sahara Occidental"', '"Western Sahara"', '"Sahara Occidental"', '"EH"', '"ESH"', '""');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Samoa"', '"Samoa"', '"Samoa"', '"WS"', '"WSM"', '"685"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Samoa Americana"', '"American Samoa"', '"Les Samoa américaines"', '"AS"', '"ASM"', '"1 684"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"San Bartolomé"', '"Saint Barthélemy"', '"Saint-Barthélemy"', '"BL"', '"BLM"', '"590"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"San Cristóbal y Nieves"', '"Saint Kitts and Nevis"', '"Saint Kitts et Nevis"', '"KN"', '"KNA"', '"1 869"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"San Marino"', '"San Marino"', '"San Marino"', '"SM"', '"SMR"', '"378"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"San Martín (Francia)"', '"Saint Martin (French part)"', '"Saint-Martin (partie française)"', '"MF"', '"MAF"', '"1 599"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"San Pedro y Miquelón"', '"Saint Pierre and Miquelon"', '"Saint-Pierre-et-Miquelon"', '"PM"', '"SPM"', '"508"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"San Vicente y las Granadinas"', '"Saint Vincent and the Grenadines"', '"Saint-Vincent et Grenadines"', '"VC"', '"VCT"', '"1 784"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Santa Elena"', '"Ascensión y Tristán de Acuña"', '"Ascensión y Tristan de Acuña"', '"SH"', '"SHN"', '"290"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Santa Lucía"', '"Saint Lucia"', '"Sainte-Lucie"', '"LC"', '"LCA"', '"1 758"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Santo Tomé y Príncipe"', '"Sao Tome and Principe"', '"Sao Tomé et Principe"', '"ST"', '"STP"', '"239"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Senegal"', '"Senegal"', '"Sénégal"', '"SN"', '"SEN"', '"221"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Serbia"', '"Serbia"', '"Serbie"', '"RS"', '"SRB"', '"381"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Seychelles"', '"Seychelles"', '"Les Seychelles"', '"SC"', '"SYC"', '"248"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Sierra Leona"', '"Sierra Leone"', '"Sierra Leone"', '"SL"', '"SLE"', '"232"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Singapur"', '"Singapore"', '"Singapour"', '"SG"', '"SGP"', '"65"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Siria"', '"Syria"', '"Syrie"', '"SY"', '"SYR"', '"963"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Somalia"', '"Somalia"', '"Somalie"', '"SO"', '"SOM"', '"252"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Sri lanka"', '"Sri Lanka"', '"Sri Lanka"', '"LK"', '"LKA"', '"94"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Sudáfrica"', '"South Africa"', '"Afrique du Sud"', '"ZA"', '"ZAF"', '"27"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Sudán"', '"Sudan"', '"Soudan"', '"SD"', '"SDN"', '"249"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Suecia"', '"Sweden"', '"Suède"', '"SE"', '"SWE"', '"46"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Suiza"', '"Switzerland"', '"Suisse"', '"CH"', '"CHE"', '"41"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Surinám"', '"Suriname"', '"Surinam"', '"SR"', '"SUR"', '"597"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Svalbard y Jan Mayen"', '"Svalbard and Jan Mayen"', '"Svalbard et Jan Mayen"', '"SJ"', '"SJM"', '""');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Swazilandia"', '"Swaziland"', '"Swaziland"', '"SZ"', '"SWZ"', '"268"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Tadjikistán"', '"Tajikistan"', '"Le Tadjikistan"', '"TJ"', '"TJK"', '"992"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Tailandia"', '"Thailand"', '"Thaïlande"', '"TH"', '"THA"', '"66"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Taiwán"', '"Taiwan"', '"Taiwan"', '"TW"', '"TWN"', '"886"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Tanzania"', '"Tanzania"', '"Tanzanie"', '"TZ"', '"TZA"', '"255"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Territorio Británico del Océano Índico"', '"British Indian Ocean Territory"', '"Territoire britannique de l\'océan Indien"', '"IO"', '"IOT"', '""');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Territorios Australes y Antárticas Franceses"', '"French Southern Territories"', '"Terres australes françaises"', '"TF"', '"ATF"', '""');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Timor Oriental"', '"East Timor"', '"Timor-Oriental"', '"TL"', '"TLS"', '"670"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Togo"', '"Togo"', '"Togo"', '"TG"', '"TGO"', '"228"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Tokelau"', '"Tokelau"', '"Tokélaou"', '"TK"', '"TKL"', '"690"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Tonga"', '"Tonga"', '"Tonga"', '"TO"', '"TON"', '"676"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Trinidad y Tobago"', '"Trinidad and Tobago"', '"Trinidad et Tobago"', '"TT"', '"TTO"', '"1 868"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Tunez"', '"Tunisia"', '"Tunisie"', '"TN"', '"TUN"', '"216"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Turkmenistán"', '"Turkmenistan"', '"Le Turkménistan"', '"TM"', '"TKM"', '"993"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Turquía"', '"Turkey"', '"Turquie"', '"TR"', '"TUR"', '"90"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Tuvalu"', '"Tuvalu"', '"Tuvalu"', '"TV"', '"TUV"', '"688"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Ucrania"', '"Ukraine"', '"L\'Ukraine"', '"UA"', '"UKR"', '"380"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Uganda"', '"Uganda"', '"Ouganda"', '"UG"', '"UGA"', '"256"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Uruguay"', '"Uruguay"', '"Uruguay"', '"UY"', '"URY"', '"598"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Uzbekistán"', '"Uzbekistan"', '"L\'Ouzbékistan"', '"UZ"', '"UZB"', '"998"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Vanuatu"', '"Vanuatu"', '"Vanuatu"', '"VU"', '"VUT"', '"678"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Venezuela"', '"Venezuela"', '"Venezuela"', '"VE"', '"VEN"', '"58"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Vietnam"', '"Vietnam"', '"Vietnam"', '"VN"', '"VNM"', '"84"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Wallis y Futuna"', '"Wallis and Futuna"', '"Wallis et Futuna"', '"WF"', '"WLF"', '"681"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Yemen"', '"Yemen"', '"Yémen"', '"YE"', '"YEM"', '"967"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Yibuti"', '"Djibouti"', '"Djibouti"', '"DJ"', '"DJI"', '"253"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Zambia"', '"Zambia"', '"Zambie"', '"ZM"', '"ZMB"', '"260"');
INSERT INTO tableName (nombre, name, nom, iso2, iso3, phone_code) VALUES ('"Zimbabue"', '"Zimbabwe"', '"Zimbabwe"', '"ZW"', '"ZWE"', '"263"');
